### ISSUE TITLE
how to disable log print ?

### ISSUE THREAD

**Issue by Awezome** [uber-go/automaxprocs#19]
how to disable log print ? thx ~

**Comment by prashantv** [comment]
Logging can only be disabled if the [underlying `maxprocs` package](https://godoc.org/go.uber.org/automaxprocs/maxprocs) is used, with the [logger option](https://godoc.org/go.uber.org/automaxprocs/maxprocs#Logger), and pass in a logger that discards the log,
```go
nopLog := func(string, ...interface{}) {},
maxprocs.Set(maxprocs.Logger(nopLog))
```

**Comment by gebn** [comment]
For the benefit of folks finding this now, it's sufficient to simply call `maxprocs.Set()` with no arguments.

**Comment by Awezome** [comment]
> 

That's cool

**Comment by Awezome** [comment]
> For the benefit of folks finding this now, it's sufficient to simply call `maxprocs.Set()` with no arguments.

That's cool
