### ISSUE TITLE
Needs readme, with bonus screenshots

### ISSUE THREAD

**Issue by sectioneight** [uber-go/automaxprocs#2]
People shouldn't land on our repos and be expected to write/run code to see what it does. Take a look at any of our other big OSS projects for a sense of what we're looking for.

cc @prashantv not sure how this got past the internal review

**Comment by jasonlai** [comment]
@sectioneight thanks for the reminder. I just merged a pull request with the clean-ups from @akshayjshah (thanks). Does this look good to you overall now?

**Comment by akshayjshah** [comment]
I've got a follow-up PR coming that changes the exported API to be a bit more explicit. It'll include a usage example for the README.

**Comment by prashantv** [comment]
We flipped this public a little early -- @akshayjshah had some changes planned and having it public made it easier to configure things like Travis etc.

**Comment by akshayjshah** [comment]
Why is everyone up between 3 and 5 am?

**Comment by akshayjshah** [comment]
Closing, since it's resolved.
