### ISSUE TITLE
Support cgroups v2 and its unified hierarchy

### ISSUE THREAD

**Issue by ajwerner** [uber-go/automaxprocs#21]
It seems from the code that this only consults the v1 cgroup and its specific subsystem. It seems that more and more code will move to using v2 cgroups and the unified hierarchy. I'm creating this issue to track support for v2 cgroups.

**Comment by jcorbin** [comment]
So at a basic / short term level, yes this library can and should support cgroups v2.

Longer term however, we'd like to get mainline support for correctly setting GOMAXPROCS within a container https://github.com/golang/go/issues/33803 and deprecate this library.

**Comment by abhinav** [comment]
Was going to reopen because the v2 support was broken, but looks like we already have #49.
