### ISSUE TITLE
comment on CPUQuotaMinUsed need to be fixed

### ISSUE THREAD

**Issue by rayzyar** [uber-go/automaxprocs#26]
Suggest to fix the comment
Change
`// CPUQuotaMinUsed is return when CPU quota is larger than the min value`
to 
`// CPUQuotaMinUsed is return when CPU quota is smaller than the min value`
https://github.com/uber-go/automaxprocs/blob/946a8391268aea0a60a86403988ff3ab4b604a83/internal/runtime/runtime.go#L31

**Comment by prashantv** [comment]
Thanks for catching the typo, agree that this should be fixed. If you can send a PR, happy to review, or this is something I can fix in a few days.
