### ISSUE TITLE
is it not default behavior after version 1.5?

### ISSUE THREAD

**Issue by huahuayu** [uber-go/automaxprocs#36]
hi, I am curious that isn't it auto set GOMAXPROCS to the cpu core number？just as [this](https://stackoverflow.com/questions/17853831/what-is-the-gomaxprocs-default-value/33451301#:~:text=Release%20Notes%20says-,By%20default%2C%20Go%20programs%20run%20with%20GOMAXPROCS%20set%20to%20the,be%20the%20number%20of%20cores.&text=Starting%20with%20Go%201.5%2C%20GOMAXPROCS,of%20CPUs%20available%20by%20default.) StackOverflow answer says, from version 1.5, it is a default behavior

**Comment by Kirides** [comment]
This package is there to ensure that Go does _not_ just set `GOMAXPROCS=numLogicalCPUs` but to honor eventual cgroup limitations / CFS quota.
This is an issue often seen with scalable containerized applications, where you do not want one app to use everything the CPU has to offer.

**Comment by huahuayu** [comment]
Okey, got it!
