### ISSUE TITLE
version 1.5.2 increased CPU consumption

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [uber-go/automaxprocs#64]
Hey folks,

I upgraded from 1.5.1 to 1.5.2 a few days ago, and I noticed an increase in CPU consumption of my service

![image](https://user-images.githubusercontent.com/16646600/227638995-f9dfc9b0-e1cc-4737-88a9-487f71e9b109.png)

I still haven't done much digging, but is there any change in this version that could be responsible for an increased CPU usage?

**Comment by rabbbit** [comment]
It would seem extremely unlikely - the code is executed once at application startup. Did the deploy contain only this change?

**Comment by AbdulRahmanAlHamali** [comment]
> It would seem extremely unlikely - the code is executed once at application startup. Did the deploy contain only this change?

Yup it was the only change there. But indeed I am surprised that this change would cause an increase in CPU. I'll do some more digging this week

**Comment by yunbj** [comment]
> > It would seem extremely unlikely - the code is executed once at application startup. Did the deploy contain only this change?
> 
> Yup it was the only change there. But indeed I am surprised that this change would cause an increase in CPU. I'll do some more digging this week

@AbdulRahmanAlHamali 
Is there any update? What about 1.5.3? Is it same?

**Comment by AbdulRahmanAlHamali** [comment]
Haven't bee following up on this unfortunately. Going to close since I don't have the data anymore
