### ISSUE TITLE
go test -cpu

### ISSUE THREAD

**Issue by jerome-laforge** [uber-go/automaxprocs#69]
I want define number of cpu  for `go test` via `-cpu`.
Is it possible to expose this library directly also as tool (with main package) that shows CPU quota in order to use it for testing?

For example, I want to do something like that:
```sh
- go install go.uber.org/automaxprocs@latest
- automaxprocs > GOMAXPROCS.txt
- go test -cpu $(cat GOMAXPROCS.txt) ./...
```

**Comment by sywhang** [comment]
You should be able to write that type of tool yourself fairly easily using this library. Use automaxprocs/maxprocs package to retrieve the cgroup limit and just print that to the console.

**Comment by jerome-laforge** [comment]
close with https://github.com/jerome-laforge/automaxprocscli/
