### ISSUE TITLE
[go.mod] Bump Go version to Go 1.21

### ISSUE THREAD

**Issue by zalgonoise** [uber-go/automaxprocs#81]
This is a placeholder issue to bump the Go version in the go.mod files and any other references, to ensure the repository references the latest versions. This is a desired change as it will include the latest security fixes and performance improvements.

As of today, the latest Go version is [Go 1.21](https://go.dev/doc/devel/release)

**Comment by dolmen** [comment]
@zalgonoise Why?

This is a bad idea as it will block projects that use a version lower than 1.21 to use this module.

**Comment by zalgonoise** [comment]
> @zalgonoise Why?
> 
> This is a bad idea as it will block projects that use a version of Go lower than 1.21 to use this module.

It is a suggestion for the security and performance improvements since Go 1.12. As time goes by, this would only become more apparent. Go's backward compatibility commitment applies to the APIs, but the runtime may change over time. 

As for this being a breaking change for certain projects, you're totally correct and I understand the reason. But for this precisely we could leverage semantic versioning and bump a major version. Older Go versions can still import maxprocs while newer ones can opt for a newer one.

Of course this is only an idea and I respect your decision, regardless. :) feel free to close this issue

**Comment by cedws** [comment]
The number in `go.mod` is just the minimum Go compiler version required to use module. It has no bearing on performance or security.
