### ISSUE TITLE
tag a release with #79 ?

### ISSUE THREAD

**Issue by dropwhile** [uber-go/automaxprocs#88]
Would it be possible to tag a new release in the near future to get the changes from #79?

**Comment by sywhang** [comment]
Certainly. We will tag a release shortly.

**Comment by sandyskies** [comment]
@sywhang when will u tag a release？ We rely heavily on this feature

**Comment by sywhang** [comment]
Released: https://github.com/uber-go/automaxprocs/releases/tag/v1.6.0
